#!/bin/sh
#
# Disable commits to the 'upstream' branch.

branch="$(git rev-parse --symbolic --abbrev-ref HEAD)"
case "$branch" in
  upstream)
    echo "Committing to branch $branch denied (override with --no-verify)" >&2
    exit 1
    ;;
esac
